README.md
Added a couple to the top of the list as an example.
I already have a list here http://griffio.github.io/engineering-tech-blogs/.
data - https://github.com/griffio/griffio.github.io/blob/master/_data/techblogs.csv
Its true they are used as marketing/recruitment blogs too but some are great resources.
=> Adzerk and AdRoll

README.md
A new Base engineering blog. We write mostly about backend, mobile, qa, infrastructure and big data.
=> Added Base engineering blog

README.md
It is mistakenly pointing to the Yelp blog.
=> Update Yammer blog address

README.md
It seems that https://github.com/nickhammond believed that removing another blog from the list without mentioning it in the pull request was a good idea.
Dear maintainer, you are free to not have monsanto's engineering blog in the list if you wish, but I thought it'd be nice to see that someone else removed it rather underhandedly.
https://github.com/kilimchoi/engineering-blogs/commit/87c75779a7ddd8e0c9abf29801b3106fca76c67f
=> Added monsanto's engineering blog

README.md
trivago (http://trivago.com) is the world biggest hotel comparison website.
The engineering department runs a techblog as well: http://tech.trivago.com/
=> Add trivago techblog

README.md
Aphyr is the personal blog of Kyle Kingsbury.
Should be moved to Individuals from Companies.
=> Aphyr - removed from Companies and moved to Individuals

README.md
Adding Mozilla Release Engineering and Automation Team blogs.
=> Adding Mozilla team blogs

README.md
Updated to show engineering only blog posts ( a number of which have been very well received on sites such as HackerNews, e.g. : https://news.ycombinator.com/item?id=9515392 ) .
=> Adding Sift Science - eng only

README.md
The Zengineering blog was not on the list, so this pull request adds it.
=> Add Zendesk to list.

README.md
Added Schibsted Tech Polska blog - http://www.schibsted.pl/blog/
=> Adding Schibsted Tech Polska Blog - http://www.schibsted.pl/blog/

README.md
Adding `Dereuromark http://www.dereuromark.de/`, a blog mainly about (Cake)PHP software developing and web software engineering.
=> Adding dereuromark.de

README.md
This commits adds Moove-it's blog to the list.
=> Add Moove-it's tech blog

README.md
Add Adam Leventhal's blog: [http://dtrace.org/blogs/ahl/](http://dtrace.org/blogs/ahl/).
=> Add Adam Leventhal's blog

README.md
Add Eli Bendersky's blog: [http://eli.thegreenplace.net/](http://eli.thegreenplace.net/).
=> Add Eli Bendersky's blog

README.md
Ilya Grigorik blog contains great articles about web performance. I think it should be added to the list.
=> Add Ilya Grigorik blog

README.md
Add Allegro.tech to list of engineering blogs (https://en.wikipedia.org/wiki/Allegro_(auction_website))
=> Add allegro to list of engineering companies

Gemfile, Gemfile.lock, contributing.md
Whilst I was making a single line contribution to this, I found I was missing gems and there was not an automated way of getting setup. To rectify this, I have added a Gemfile and notes in the contributing guidelines for users to run `bundle install` instead of needing to go through the require statements and
install them manually.
If you're not a fan of bundler or don't think this is required, feel free to ignore this pull request. :)
=> Add Gemfile for dependencies and update how get setup

README.md, engineering_blogs.opml
Pat Shaughnessy is a prominent Rubyist. He usually [blogs](http://patshaughnessy.net) about Ruby/Rails internals. he has also written a book - [Ruby under microscope](http://patshaughnessy.net/ruby-under-a-microscope). I suggest adding his blog to the list.
=> Added Pat Shaughnessy's blog

README.md
Thanks for the effort, @duckspeaker - but the official name of my blog is "Leo" and not "Leonard Lamprecht".
I know this might be a bit confusing (particularly because I didn't change the logo text yet), but there are some good reasons I didn't name it after my full name, primarily because it's just too hard to pronounce.
I already changed my domain and the `<title>` tag to the new name and will also make sure the logo fits it soon. Sorry for the confusion! :)
=> Changed title back to nickname

README.md, engineering_blogs.opml
As tittled.
I add Stack Exchange company blog. The link of this blog points out to http://blog.stackexchange.com/engineering. But, the feed points out to http://blog.stackexchange.com/feed/ (all new content of the blog).
=> add stackexchange blog

README.md, engineering_blogs.opml
Hi,
I'm adding [technical blog of Future Processing](http://www.future-processing.pl/technical-blog/) company to the list. Articles on the blog are technical, written in English and related to different areas of software development. I've read contribution guidelines and generated record in `engineering_blogs.opml` file.
Regards,
Piotr
=> Adding technical blog of Future Processing company

contributing.md
Related to PR #305 
Enforcing single commits for every PR can have a negative impact on the project. It's more process for contributors and maintainers to follow, and increases the time it takes to get changes into the codebase. Trust that contributors will squash when appropriate.
=> Only squash commits when appropriate

README.md, engineering_blogs.opml
According to [this news](http://blog.stackoverflow.com/2015/09/were-changing-our-name-back-to-stack-overflow/), __Stackexchange__ is changing its company name back to __Stack Overflow__. So, I proposed this pull request to update the company name and domain.
=> change company name and domain of Stackexchange

README.md, engineering_blogs.opml
As titled.
But, one thing I don't know, why was Jolly Good Code deleted by program?
It is included in the list of blogs where program doesn't able to find the RSS location.
=> Add We Are Wizards's blog

README.md, engineering_blogs.opml
Please consider to add these site... thanks
* Piotr Pasich is a PHP Developer, writes a lot about Symfony PHP Framework and web development related
* Rob Allen is a PHP and Zend Framework expert based in Worcester, UK. He runs Nineteen Feet, is the author of Zend Framework in Action.
=> Add Piotr Pasich and Rob Allen to individual lists

README.md
Official AWS blog is very technical, covering wide variety of engineering topics. I was surprised to not see it in this list.
=> Adding AWS blog

engineering_blogs.opml
For feeds that where giving a 404 error, I went through common feed names / used the RSS meta to find the new one.
LinkedIn and Slideshare don't seem to have a feed at all anymore so have been removed.
=> Fix 404 Feeds

README.md, engineering_blogs.opml
After generating OPML, there is a list that contains missing RSS blogs. I checked and fixed some manually. This is what I did:
* Remove Prismatic, I removed it because its link is dead.
* Change Pamela Fox's blog URL, I changed it to grab the RSS feed.
* Add Paul Graham's RSS feed manually, I saw there is one.
Thanks.
=> Fix missing RSS blog

README.md
Keep products/technologies as the section but use the more general
technologies instead of products for the subsection labels.
=> rename products subsections to technologies

README.md, engineering_blogs.opml
Rss feed links are dead and technical content SNR is low.
=> remove peter lyons

engineering_blogs.opml
I just fixed Xoom blog's RSS feed manually. I have tested it by running the `generate_opml.rb" file.
The RSS feed of this blog exists. Please, review this!
Thank you.
=> Fix Xoom blog's RSS feed

README.md, engineering_blogs.opml
The blog address is changed from http://rubylogs.com to http://eftimov.net.
Please, review! Thank you.
=> Change Ilija Eftimov's blog address

README.md
Ran `generate_opml.rb` but nothing was added for this new entry, however, it generated a bunch of entries to `engineering_blogs.opml` from prior additions that may not have run the ruby script.  I manually deleted these unrelated entries since they aren't related.
=> Add Nick Galbreath

README.md, engineering_blogs.opml
Anyone can create a company and make a website for it, but if the
website is blatantly for a company with a single individual, it should
be under Individuals.
=> Move DataRadar to Individuals

README.md, engineering_blogs.opml
It seems Instagram engineering's blog that located at http://instagram-engineering.tumblr.com/ is outdated. I have compared it with Instagram engineering's blog that located at http://engineering.instagram.com/. The old one is updated 8 months ago.
What do you think?
=> Change Instagram engineering's blog address

README.md, engineering_blogs.opml
Added link to the Opendoor engineering blog.
opml script updated the subdomain for Michael Crump's blog.
=> add Opendoor engineering blog

README.md, engineering_blogs.opml
I think their certification is valid now. And sorry for the extra commit about non-ascii.
=> Added 500px Dev

engineering_blogs.opml, generate_opml.rb
Sometimes the generate opml script is going to repeatedly pick things up
we want it to ignore. Create a temp ignore list to avoid this.
=> add temp ignore list

README.md, engineering_blogs.opml
The new re-imagined engineering blog from WalmartLabs on Medium with brand new content - “Real, on the ground stories from real engineers.”
https://medium.com/walmartlabs
WalmartLabs engineering has been suggested before and rejected; now it's back with "real" content.
=> Adds WalmartLabs engineering blog and rss feed

README.md, engineering_blogs.opml
Klipse's blog is a blog behind [Klipse library][1]. This blog contains various posts about functional programming. Please review!
[1]: https://github.com/viebel/klipse
=> Add Klipse's blog

README.md, engineering_blogs.opml
The URL of Stack Overflow blog has changed. When you access http://blog.stackoverflow.com, it will be directed to https://stackoverflow.blog.
=> Update URL of Stack Overflow blog

README.md, engineering_blogs.opml
The recently launched Semaphore Engineering blog features technical posts by product engineers. Existing entry for Semaphore Community includes articles on TDD, CI/CD and DevOps from various contributors.
=> Add Semaphore CI Engineering blog.

README.md, engineering_blogs.opml
Novoda is a product-engineering agency specialising in mobile software engineering. 
Novoda is a recognised industry-leader in best-practise for mobile software engineering, being one of only a few [Google Certified Agencies](https://developers.google.com/agency/directory/) and employing a large number of [Google Developer Experts](https://developers.google.com/experts/). Its posts cover iOS, Android, Firebase, and occasionally other technologies in the mobile sector such as React Native.
Disclosure: I'm the Head of Product for Novoda.
=> Added Novoda blog

README.md
Skyscanner runs the [Codevoyagers](http://codevoyagers.com/) blog, added under engineering.
=> Add Skyscanner Engineering blog

README.md
The jOOQ blog mostly talks about:
- What it takes to implement jOOQ (e.g. JDBC specifics)
- Java language stuff (e.g. how generics and overloading work)
- API design stuff (e.g. best practices for backwards compatibility)
- SQL stuff and tricks (e.g. how to do XY in SQL)
I think it qualifies, given that probably more than 80% is technical and less than 20% is really about jOOQ. Some popular examples:
- https://blog.jooq.org/2014/08/12/the-difference-between-row_number-rank-and-dense_rank/
- https://blog.jooq.org/2016/03/17/10-easy-steps-to-a-complete-understanding-of-sql/
- https://blog.jooq.org/2014/12/04/do-you-really-understand-sqls-group-by-and-having-clauses/
- https://blog.jooq.org/2016/04/25/10-sql-tricks-that-you-didnt-think-were-possible/
- …
=> Add jOOQ Engineering blog

engineering_blogs.opml
The Heroku Engineering Blog was moved, this commit changes the URL to the correct one.
=> change Heroku Engineering Blog url

README.md, engineering_blogs.opml
I just checked that accessing Strava's engineering blog (http://labs.strava.com/blog/) will redirect you to https://medium.com/strava-engineering/. Please, review this pull request!
Thank you.
=> Update Strava's engineering blog address

README.md
This PR adds latest Zendesk's engineering blog address and marks the old address as `old`.
=> Update Zendesk's engineering blog address

README.md, engineering_blogs.opml
These website are returning a DNS errors.
- AlphaSights http://engineering-blog.alphasights.com/
- Flipkart http://tech-blog.flipkart.net/
=> Remove AlphaSights and Flipkart blogs due to DNS errors

engineering_blogs.opml
Hi,
When I import OMPL file to Feedly, I found these blogs have broken links:
- DeferPanic
- Funding Circle
So I fixed it. Please check.
=> Fix broken feed url of FundingCircle & DeferPanic

README.md
There are no records for `blog.linkedcare.com` (`dig @8.8.8.8 a blog.linkedcare.com` yields no answers), and they don't seem to have moved the blog elsewhere.
=> Remove Linkedcare

README.md, engineering_blogs.opml
I have (automatically) checked all URLs, and updated the (non-secure HTTP) URLs of blogs that now default (i.e. 301 Permanent Redirect) to HTTPS.
=> Update URLs of blogs that now default to HTTPS

README.md
It seems this website is down. When I try to load this website, it says unable to connect.
=> Remove Ducode.org

README.md
Add the engineering blog of Graphcool.
Homepage of company: [here](http://www.graph.cool/)
=> Add Graphcool blog

README.md
The asos techblog seems to be gone, I couldn't find a new address.
=> Remove non-existent asos techblog

README.md, engineering_blogs.opml
* This adds an entry to  UpGrad's new engineering blog.
* The blog includes challenges and lessons that we have learned as part of building and maintaining an online learning platform engaging with 150k+ students.
* In case you are interested, you can have a look at one of our posts https://engineering.upgrad.com/turn-your-website-testing-painless-with-chrome-and-firefox-headless-92b6f023d375
=> Added UpGrad Engineering

README.md, engineering_blogs.opml
This is an existing blog in the library that has updated its URL. The content still meets the desired criteria (company blog that is 80% or more technical posts).
=> Updating URL for Condé Nast Technology (formerly Engineering) blog

README.md
About this blog:
"...I'm Steve Bellovin — my login is smb, hence the name of this blog — and I'm a professor of computer science. My primary research focus is computer and Internet security, but I have a strong interest in privacy and related issues...."
=> Adding Blog of Steve Bellovin

engineering_blogs.opml
Edward Faulkner blog consists many thoughtful posts on Abstraction , Interfaces and frameworks and Edward is a member of the Ember Core Team .
=> added Edward Faulkner

README.md, engineering_blogs.opml
Related with #880, EBay has changed their URL to https://www.ebayinc.com/stories/blogs/tech/, and we should put the tech one instead the news.
=> Update EBay link

README.md, engineering_blogs.opml
We have a new blog that deals with deeper technical content, and content that is not just related to Docker software but our internal engineering processes as well.
=> Add Docker Engineering specific blog

README.md, engineering_blogs.opml
The old ones were leading to the general blog, while this one is exclusively maintained by the engineering team at Hashnode.
=> Fixing Hashnode engineering links

README.md, engineering_blogs.opml
We noticed our redirect from the old URL wasn't working, so I've updated the link to the new one. Cheers!
=> REA Group - our tech blog has moved.

README.md, engineering_blogs.opml
Add codewithoutrules, a blog about programmer productivity with ~4000 subscribers.
=> Add codewithoutrules

README.md, engineering_blogs.opml
Docker engineering link redirects to the same link as Docker link. It is now a duplicate link.
=> Duplicated Docker engineering link
