kilimchoi/engineering-blogs

README.md

Takipi blog - Java and Scala devs

Added Takipi

---

README.md

The blog is pretty new but potentially worth including? [KA Engineering](http://engineering.khanacademy.org)

Add Khan Academy.

---

README.md

Added: * Periscope-https://www.periscope.io/blog/

Added Periscope.io engineering Blog - High Performance SQL

---

README.md

Good Eggs brings local, farm-fresh groceries right to your door: https://www.goodeggs.com
I added the Engineering blog.

Added Good Eggs engineering blog

---

README.md

They write a lot about security / oauth / api authentication / etc.

Adding stormpath's engineering blog to the list.

---

README.md

I have added Martin Fowler's personal blog.
Please, review!
Thank you.

add Martin Fowler's weblog

---

README.md

A lot of JavaScript / NodeJS / AngularJS / software testing / architecture / people / productivity blog posts (more than 200 posts in less than two years)

Adding link to Gleb Bahmutov's blog

---

README.md

Added Vine's Engineering Blog.

Add Vine's Engineering Blog.

---

README.md

Add Zach Holman blog

---

README.md

Adding EverythingMe Geeks Blog

---

README.md

Security, JavaScript, and Web topics : http://engineering.shapesecurity.com/
Thanks!

added shape security's eng blog

---

README.md

* remove java category request param on Rent the Runway link

* fix the ordering of some of the items

---

README.md

Adding BloomReach engineering blog

---

README.md

The old one has great topics as well

Add GitHub's former engineering blog

---

README.md

Adding MemSQL engineering blog.

Added engineering blog of MemSQL.

---

README.md

Added OpenTable tech blog.
http://tech.opentable.com/

Added OpenTable tech blog

---

README.md

A blog on DB and Distributed systems.

Adding Nicolas Liochon's blog

---

README.md

Hi,
I'm not working with Atlasssian but I'm working in Sydney and Atlasssian is the best tech company here in Australia and worth sharing it.
Mint

Add Atlassian Developer Blog

---

README.md

Somehow it ended up in the individual contributors bucket :)

Redbubble is a Company

---

README.md

Missed the blog of Android Wharton

Added Jake Wharton's blog

---

README.md

Such Blog
Many Article
Much Content

Adds Blundells Android Blog

---

README.md

Add link to Bill The Lizard Blog

Add a link to Bill the Lizard's Blog

---

README.md

Member of the Google Chrome team

Add Paul Irish to list

---

README.md

the blog mostly has tutorials or programming related posts. thanks!

Added Codementor Blog

---

README.md

Web, Cloud, Mobile Application Development

Adding Devgirl's weblog

---

README.md

hey @kilimchoi - as far as i can tell, the name and the in

Added Prolific Interactive blog

---

README.md

Added Flipkart tech blog

---

README.md

95% of posts are technical, new entries are created twice a week with quality tech content

Add Binary Studio blog

---

README.md

Add the Hootsuite Engineering technical blog.

Add Hootsuite.

---

README.md

I would like to add in my tech blog.

add winston chen in

---

README.md

Added Engine Yard(PaaS) and Criteo(Ad) tech blogs.

Added EngineYard and Criteo

---

README.md

Alphabetical order added

---

README.md

* https://www.zalando.de
* https://tech.zalando.com

Added Zalando

---

README.md

Add Dave Cheney blog: [http://dave.cheney.net/](http://dave.cheney.net/).

Add Dave Cheney's blog

---

README.md

I've added our team's blog(hungry geek) to the list. 
Great job on getting this together :+1:

Add holiday extras to list of blogs

---

README.md

Add TaskRabbit's engineering blog; Add Evan's personal blog.

Add TaskRabbit's engineering blog; Add Evan's personal blog.

---

README.md

Adding mine about programming and open source:
* [radek.io](http://radek.io)

Adding Radek Pazdera

---

README.md

Magnet.me is a recruitment platform in the Netherlands. We recently started blogging. We have more blog posts lined up about microservices and reactive programming. It's 100% technical.

Add Magnet.me tech blog

---

README.md

Mostly technical posts (some are less technical) here from our engineering team.

Add theScore's techblog

---

README.md

Add [Localytics](http://www.localytics.com/)' [Engineering Blog](http://eng.localytics.com/).

Add Localytics' engineering blog.

---

README.md

Add Ticketmaster's engineering/tech blog.

---

README.md

Added [Zumba](https://www.zumba.com)'s [tech blog](http://tech.zumba.com).

Add Zumba's tech blog.

---

README.md

Added the AWeber Engineering blog, and my personal blog.

Add AWeber and personal blog

---

README.md

Add Fatih Arslan's blog: [http://arslan.io/](http://arslan.io/).

Add Fatih Arslan's blog

---

README.md
engineering_blogs.opml

This adds [Envato](http://envato.com) to the list of blogs.

Add Envato to the list of available blogs

---

README.md
engineering_blogs.opml

Added Recruiterbox Engineering blog

added Recruiterbox

---

README.md
engineering_blogs.opml

Addy Osmani's blog contains valuable information about Frontend development.

Add Addy Osmani blog

---

README.md
engineering_blogs.opml

Lea Verou's blog contains interesting posts about JavaScript and CSS.

Add Lea Verou blog

---

README.md
engineering_blogs.opml

Kent Beck's blog contains fascinating articles about software development.

Add Kent Beck blog

---

README.md
engineering_blogs.opml

Adding two technology blogs by [Myntra](http://myntra.com); Software engineering, Open Source and Data science.

Myntra Engineering and Data Sciences

---

README.md
engineering_blogs.opml

I've added my blog Ducode.org, and only specific the "tutorial" tag since not all posts on my blog are technical. I've written some tutorials which have been received well by some people. Is my blog good enough for the list?

Added Ducode.org to readme and RSS

---

README.md
engineering_blogs.opml

Brendan Eich is known as the creator of JavaScript. I suggest adding his blog to the list.

Add Brendan Eich blog

---

README.md
engineering_blogs.opml

Added LiveRamp's engineering blog

Added LiveRamp's engineering blog

---

README.md
engineering_blogs.opml

Added "LINUX, EMBEDDED, ANDROID AND SECURITY BLOG"

Adding Ramon Fried's Engineering blog

---

README.md
engineering_blogs.opml

Added the XO Group Technology team's blog.

Add XO Group

---

README.md

Works at Google on the Chrome Developer Relations team as an advocate.

Paul Lewis added

---

README.md
engineering_blogs.opml

I'm submitting my blog, which is mostly about front end development. Thanks :) and very nice effort organizing this! :star2:

Add Guilherme Rodrigues

---

README.md
engineering_blogs.opml

A freelance developer who shares great web development tutorials.

Add Michael Herman's blog

---

README.md
engineering_blogs.opml

Moved Eric Lippert's blog from companies to individuals.
Added Adam Tuliper's blog.

Added Adam Tuliper's blog and moved Eric Lippert's blog

---

README.md
engineering_blogs.opml

xoom dev blog added to glorious list.
opml file was stale updated it.

xoom added to company section and refreshed opml file

---

README.md
engineering_blogs.opml

Added
http://developers.500px.com
http://developers.500px.com/feed

Added 500px engineering blog and updated opml

---

README.md
engineering_blogs.opml

Added
https://engineering.opendns.com/
https://engineering.opendns.com/feed

Added openDNS engineering blog and updated opml

---

README.md
engineering_blogs.opml

Added
http://www.drivenbycode.com/
http://www.drivenbycode.com/feed/

Added TrueCar engineering blog and update opml

---

README.md
engineering_blogs.opml

I have been blogging about technical libraries and ideas during my recent initiative: [A year of Commits](jakeyesbeck.com/2015/04/23/a_year_of_commits)
The most recent post is not as technical but many other are, like [this one](http://jakeyesbeck.com/2015/06/21/validates_subset/) and [this one](http://jakeyesbeck.com/2015/05/31/wrapping_apis/)

Add Jake Yesbeck

---

README.md
engineering_blogs.opml

Added
http://engineering.datarank.com/
http://engineering.datarank.com/feed.xml

Added datarank engineering blog and updated opml

---

README.md
engineering_blogs.opml

Added
http://www.eharmony.com/engineering/
http://www.eharmony.com/engineering/feed/

Added Eharmony engineering blog and updated opml feed

---

README.md
engineering_blogs.opml

Added
http://engineering.sharethis.com/
http://engineering.sharethis.com/rss

Added sharethis engineering blog and updated opml

---

README.md
engineering_blogs.opml

Added
http://engineering-blog.alphasights.com/
http://engineering-blog.alphasights.com/rss

added alphasights engineering blog and updated opml

---

README.md
engineering_blogs.opml

Added
http://tech.transferwise.com/
http://tech.transferwise.com/rss/

Added Transferwise engineering blog and updated opml

---

README.md
engineering_blogs.opml

I'm a French IT engineer working mainly on Rails and Node, and i wrote english technical articles, mainly 'beginer' ones. 
Great job with this list!
Cheers,

Add rdlh.io

---

README.md
engineering_blogs.opml

Added
http://engineering.wingify.com/
http://engineering.wingify.com/atom.xml

Added Wingify engineering blog and updated opml

---

README.md
engineering_blogs.opml

Added
http://engineering.speedledger.com/
http://engineering.speedledger.com/feed/

Added Speedledger engineering blog and updated opml

---

README.md
engineering_blogs.opml

Added
http://engineering.laterooms.com/
http://engineering.laterooms.com/rss/

Added Laterooms engineering blog and updated opml

---

Gemfile.lock
README.md
engineering_blogs.opml

Have added Skcript's blog. http://blog.skcript.com/

Adding Skcript's blog

---

README.md
engineering_blogs.opml

Added
http://engineering.klout.com/
http://engineering.klout.com/feed/

Added klout engineering blog and update opml

---

README.md
engineering_blogs.opml

This is my 100% technical blog. I mostly write about programming and I try to make it easy for everyone to understand. The full url is: http://www.blackbytes.info/

Add blackbytes.info

---

README.md
engineering_blogs.opml

Hi, all.
I have added some individual contributors into engineering-blogs. They are Aaron Patterson, Blake Erickson, Robin Ward, and Sam Saffron. Please, review my work!
Thank you.

add some individual contributors

---

README.md
engineering_blogs.opml

I just add Ariya Hidayat's blog. Please, review the blog link first!
Thank you.

add Ariya Hidayat's blog

---

Gemfile.lock
README.md
engineering_blogs.opml

Added.
http://developers.linecorp.com/blog/
http://developers.linecorp.com/blog/?feed=rss2

Added LINE engineering blog and updated opml

---

README.md
engineering_blogs.opml

As titled.
I add Petr Mitrichev's blog. Petr Mitrichev publishes new post about algorithm based on his competition and other thing each week. Please, review this blog first!
Thank you.

add Petr Mitrichev's blog

---

README.md
engineering_blogs.opml

Hi,
I'm adding my personal technical blog, which is available at: http://blog.wittchen.biz.pl/.
It touches various technical areas like Java, Android, Python, software development process and more.
I hope, you'll find it useful.
Regards,
Piotr

adding blog.wittchen.biz.pl

---

README.md
engineering_blogs.opml

As titled.
I just added Matt Might's blog. Please, review it!
Thank you.

add Matt Might's blog

---

README.md
engineering_blogs.opml

I add another individual contributors, Kevin Burke and Nic Raboy.
Nic Raboy has amazing post about developing application using Ionic Framework. Kevin Burke too.
Please, review this PR!
Thanks.

add Kevin Burke and Nic Raboy

---

README.md
engineering_blogs.opml

Please, review the blog http://nikolay.rocks/ first!
Thanks.

add Nikolay Nemshilov's blog

---

README.md

Added Zulily http://engineering.zulily.com/ 
I could not run the OPML generator due to issues with my Ruby installation.

Added Zulily http://engineering.zulily.com/

---

README.md
engineering_blogs.opml

Added Andrey Akinshin's blog

---

README.md
engineering_blogs.opml

Very new but I subscribed. It should be good

added IFTTT engineering

---

contributing.md

I saw there are some pull requests that contain two or more commits. As a common practice, it's recommend that contributors squash all their commits into one commit for each PR they submit.
I look there are many open source projects mostly using this rule. This is just an idea.
What do you think guys? 
Note: I should create an issue first before I make this pull request. Sorry, I did this hurriedly.

add new pull request rule

---

README.md
engineering_blogs.opml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kilimchoi/engineering-blogs/306)

Add Stefan Parker blog (facebook engineer)

---

README.md
engineering_blogs.opml

VNGRS is a technology company which works with Scala, Ruby and Java on
Machine Learning, Recommendation Engines, Data Mining, Big Data, etc.
It's also partner of Typesafe.

VNGRS blog is added into the list

---

README.md
engineering_blogs.opml

Add Mixmax eng team blog.

---

README.md
engineering_blogs.opml

He blogs in the Web Science context, authored JSON-LD.

Added Manu Spornys Blog

---

README.md
engineering_blogs.opml

It's more of a scientific blog than engineering, but i believe it's worth to be on the list.

add-Idontgetoutmuch

---

README.md
engineering_blogs.opml

As tittled.
Huon on the Internet is belong to Huon Wilson. He posts about Rust programming language mainly.
Please, review this pull request! Thank you.

add Huon on the Internet

---

README.md
engineering_blogs.opml

As titled.
I just added Dennis Yurichev's blog. This author mainly talks about reverse engineering, programming, and mathematic. Please, review this pull request!
Thank you :smile: 
Note: Github Old blog is replaced with a new RSS. I don't know the history of it.

Add Dennis Yurichev's blog

---

README.md
engineering_blogs.opml

added walmart labs

---

README.md
engineering_blogs.opml

As titled. Please, review this pull request!
Thanks.
I edited this title because I just squashed my commit into one.

add Andrew Ray and Ruslan Spivak blogs

---

README.md
engineering_blogs.opml

My site's domain recently changed.

New Domain

---

README.md
engineering_blogs.opml

@una's blog (http://una.im) has some really good technical (and general development/design) posts.

Add blog of Una Kravets

---

engineering_blogs.opml
generate_opml.rb

I made a simple modification to the generator script. Now it is possible to display not responding URLs. 
Future work could include a better formatting and generating a report file.

Added functionality to display not reponding blogs and updated the list.

---

README.md
engineering_blogs.opml

As titled.
Please, review the blog I just proposed!
Thank you.
**Note**: Please, don't close the pull request if one of them is not technical blog! Tell me why the blog is not included!
I will change my pull request by pushing another commit on the same branch (to make the history of commit and PR clean).

add some individual blogs

---

README.md
engineering_blogs.opml

Added Stack Abuse blog to "individuals" list. Please let me know if you have any questions or need anything changed. Thanks!

Added Stack Abuse blog to Individuals list

---

README.md
engineering_blogs.opml

add bigstep blog, almost of their articles related to server and bigdata
add Srinivas Tamada on individual list, well known as 9lessons.info

add Srinivas Tamada (9lessons.info)

---

README.md
engineering_blogs.opml

please add this, this blog contains so many useful articles

Add blog of Federico Cargnelutti

---

README.md
engineering_blogs.opml

Undocumented Matlab: http://undocumentedmatlab.com/
No connection to the site/author but it's been really helpful and interesting to me and my research.

Added: Undocumented Matlab

---

README.md
engineering_blogs.opml

Here below are individual contributors I proposed:
- Andrew Brampton
- Jamis Buck
- Wilfred Hughes
Thank you so much.

add some individual contributor blogs

---

README.md
engineering_blogs.opml

Small amendment I added from my own list.
Zenpayroll are now called Gusto. 
Seems naming companies is getting more esoteric ;)

Gusto added - Zenpayroll removed

---

README.md
engineering_blogs.opml

As titled.
I am afraid, Robert Elder Software RSS got errors when the program was getting that.

Add Robert Elder Software and Nelson Elhage

---

README.md
engineering_blogs.opml

Add Jolly Good Code's blog to companies

---

README.md

Blog posts look to be 95%+ engineering based. Primary focus on web programming.

Added the Zenefits blog, good reads on web programming

---

README.md
engineering_blogs.opml

Recommended to add, please consider this site. thanks

Add Dragan Gaic (Gajotres.net)

---

README.md

added Redino http://redino.net/blog

added Redino http://redino.net/blog

---

README.md
engineering_blogs.opml

Hello!
I'd like to add my blog to this very good list.

Add Miguel Quinones' blog

---

README.md
engineering_blogs.opml

This pull request adds <a href="https://blog.chaps.io/">Chaps.io blog</a> to the list.

Added Chaps blog

---

README.md
engineering_blogs.opml

Add Plataformatec and nate berkopec

Add Plataformatec and nate berkopec

---

README.md
engineering_blogs.opml

Please add Josh Sherman (http://joshtronic.com/), you can see his repo https://github.com/joshtronic for reference who he is

Add Josh Sherman (http://joshtronic.com/)

---

README.md
engineering_blogs.opml

(edited) I just add Chris Hager's blog.
Thanks.

Add ReactJS News and Chris Hager's blog

---

README.md
engineering_blogs.opml

I just added Mykhailo Kozik's blog.
Thank you.

Add Mykhailo Kozik's blog

---

engineering_blogs.opml

Does not need the /blog on the end

Cloudera blog location

---

README.md
engineering_blogs.opml

[Wolox](http://www.wolox.com.ar) is a startup devoted to innovating the way in which technological startups are created.

Adds Wolox's engineering blog

---

README.md
engineering_blogs.opml

Hey, we recently started tech blog at SecretEscapes. Not much there yet, but will be pure dev&design thing.

added Secret Escapes tech team blog

---

README.md

Disclaimer: I am adding [my own blog](http://tomassetti.me)
I checked before to ask if that was alright (#409)

Add Federico Tomassetti software engineering blog

---

README.md
engineering_blogs.opml

Add Codemancers and TrackMaven engineering blog

---

engineering_blogs.opml

* add rss for robert elder
* adjust position of semaphore CI

opml adjustments

---

README.md
engineering_blogs.opml

Remove Devmag.io

---

README.md
engineering_blogs.opml

Remove AWeber.

---

README.md
engineering_blogs.opml

There are only two posts and they date back to 2014.

Remove 2359 Media.

---

README.md
engineering_blogs.opml

remove nerdish by nature

---

README.md
engineering_blogs.opml

remove rent the runway

---

README.md
engineering_blogs.opml

remove underarmour

---

README.md
engineering_blogs.opml

remove trello

---

README.md
engineering_blogs.opml

remove xo group

---

README.md
engineering_blogs.opml

remove zesty

---

README.md
engineering_blogs.opml

Remove a list apart.

---

README.md
engineering_blogs.opml

Not enough [post-2012] content.

Remove ajaxian.

---

README.md
engineering_blogs.opml

Remove Dan North.

---

README.md
engineering_blogs.opml

remove michael becker

---

README.md
engineering_blogs.opml

adding Intercom Engineering Blog

---

contributing.md

* Reorder items in contributing file.
* Add one pull request per add rule.

update contributing file

---

README.md
engineering_blogs.opml

Add Jane Street's blog

---

README.md
engineering_blogs.opml

running generate_opml.rb appears to have added Xoom to the OPML file as well as the intended Sky Betting & Gaming addition.

add Sky Betting & Gaming

---

README.md
engineering_blogs.opml

Add Benchling's engineering blog

---

engineering_blogs.opml

Deleted opml file and ran generation script.

update opml file

---

README.md
engineering_blogs.opml

Please this blog, he has a lot of useful articles about web server related (about nginx mostly), very useful for webdev

Add Bjørn Johansen (https://bjornjohansen.no/ )

---

README.md
engineering_blogs.opml

As titled.
Please, review this pull request! Thanks.

Add Josh Haberman's blog

---

README.md
engineering_blogs.opml

remove EverythingMe

---

README.md
engineering_blogs.opml

Please, review this pull request!
Thank you.

Add HireArt's blog

---

README.md
engineering_blogs.opml

added individual blog address (ggajos.com)

added individual blog address

---

README.md
engineering_blogs.opml

As titled.
Please, review! Thanks.

Add Crystal programming language's blog

---

README.md
engineering_blogs.opml

Whois info:
```
$ whois winstonchen.co
Domain Name:                                 WINSTONCHEN.CO
Domain ID:                                   D64892677-CO
Sponsoring Registrar:                        GODADDY.COM, INC.
Sponsoring Registrar IANA ID:                146
Registrar URL (registration services):       www.godaddy.com
Domain Status:                               clientDeleteProhibited
Domain Status:                               clientRenewProhibited
Domain Status:                               clientTransferProhibited
Domain Status:                               clientUpdateProhibited
Domain Status:                               expired
Registrant ID:                               CR188437217
Registrant Name:                             Winston Chen
Registrant Address1: …
```

Remove Winston Chen whose domain expired

---

README.md
engineering_blogs.opml

As titled.
Please review! Thank you.

Add Teamwork's engineering blog

---

README.md
engineering_blogs.opml

As titled.
Please, review! Thank you.

Add Abu Ashraf Masnun's blog

---

README.md
engineering_blogs.opml

As titled.
K. Harrisson's blog is mainly discussed about iOS development. Please, review this pull request!
Thank you.

Add K. Harrison's blog

---

README.md
engineering_blogs.opml

As titled.
Scrunch's tech blog: https://tech.scrunch.com/blog/
Please, review this pull request!
Thank you.

Add Scrunch's tech blog

---

README.md
engineering_blogs.opml

As titled.
Evil Martians's blog: https://evilmartians.com/chronicles/. Please, review this pull request!
Thanks.

Add Evil Martians's blog

---

README.md
engineering_blogs.opml

As titled.
Toptal's blog contains software engineering posts and programming tutorials.
Please, review this pull request!
Thank you.

Add Toptal's blog

---

README.md
engineering_blogs.opml

Site misconfigured (invalid cert).

remove 500px

---

README.md

Hi,
It would be great if you would add my blog to this.
Regards,
Evan

Added Evan Dempsey blog - www.smallsurething.com

---

README.md
engineering_blogs.opml

Site times out, slowing down opml generation script.

remove rdio

---

README.md
engineering_blogs.opml

move Swift to Products/Technologies

---

README.md
engineering_blogs.opml

I added Filippo Valsorda's blog. This is the URL of blog https://blog.filippo.io/.
Please, review this one!
Thank you.

Add Filippo Valsorda's blog

---

README.md
engineering_blogs.opml

added intel blogs

---

README.md
engineering_blogs.opml

I just added Segment's blog on engineering category. Please, review!
Thank you.

Add Segment's blog

---

README.md
engineering_blogs.opml

As titled.
added wso2 : http://wso2.com/library/. Please, review this pull request!
Thanks.

added wso2

---

README.md
engineering_blogs.opml

Just added Vena Solutions's engineering blog. Please, review this pull request!
Thank you.

Add Vena's engineering blog

---

README.md
engineering_blogs.opml

As titled.
Please, review this pull request!

Add Vevo's engineering blog

---

README.md
engineering_blogs.opml

As titled.
I just added Zoosk's engineering blog.

Add Zoosk's engineering blog

---

README.md
engineering_blogs.opml

I just added Panorama Education's blog. Please, review this blog!
Thank you.

Add Panorama Education's engineering blog

---

README.md
engineering_blogs.opml

Add Kinvolk's blog

---

README.md

remove xoom

---

README.md

Added T.J. Maher, http://adventuresinautomation.blogspot.com/

T.J. Maher

---

README.md
engineering_blogs.opml

As titled.
Please, review this blog contents. Thank you.

Add Atomic Object's blog

---

README.md
engineering_blogs.opml

Just added Slack's engineering blog. Please, review the content of the blog!
Thank you.

Add Slack's engineering blog

---

README.md

Added appnexus

---

README.md
engineering_blogs.opml

Added Codelitt's blog. Please, review the content of the blog!
Thank you.

Add Codelitt's blog

---

README.md
engineering_blogs.opml

Added individual contributor blog, Clay McLeod.
Please, review this blog! Thank you.

Add Clay McLeod's blog

---

README.md
engineering_blogs.opml

Add Matt Warren's blog

---

README.md
engineering_blogs.opml

As titled.
Needs review.
Thank you.

Add blogfoster's engineering blog

---

README.md
engineering_blogs.opml

Add Juan Treminio, a Texas-based web developer blog
but he doesn't implement RSS on his blog, but its very nice to put him on the list

Add Juan Treminio https://jtreminio.com

---

README.md
engineering_blogs.opml

Add Dot Dev (.dev), its sitepoint alike, so random topic but still related with development

Add Dot Dev https://dotdev.co

---

README.md
engineering_blogs.opml

As titled. Please, review this entry!
Thank you.

Add Dennis Felsing's blog

---

README.md

Added King Tech Blog to the list of company blogs

---

README.md
engineering_blogs.opml

As titled. This PR needs review.
Thanks.

Add Advanced Web Machinery's blog

---

README.md
engineering_blogs.opml

Add Budacode's blog

---

README.md
engineering_blogs.opml

As titled. Needs review.
Thanks.

Add Chen Hui Jing's blog

---

README.md
engineering_blogs.opml

Hi guys,
Please include my personal blog about JavaScript https://rainsoft.io.
Check the [posts archive](https://rainsoft.io/archive-post/).
Thanks!

Add Dmitri Pavlutin blog https://rainsoft.io

---

engineering_blogs.opml

clean up opml

---

README.md

remove kifi

---

README.md

remove arslan.io

---

README.md

remove humblecoder

---

README.md
engineering_blogs.opml

remove technotalkative

---

engineering_blogs.opml

remove WyeWorks rss feed

---

README.md

Just wanted to add my blog as well :)
I mostly write about web technologies, software architecture and coding best practices (testing and stuff).
cheers

Add Juri Strumpflohner's blog

---

README.md
engineering_blogs.opml

Adding company: RetailMeNot

---

README.md

According to wikipedia, https://en.wikipedia.org/wiki/List_of_largest_Internet_companies, Expedia is part of the largest Internet Companies.

Add Expedia to the list

---

README.md
engineering_blogs.opml

Technical Articles on Cloud Foundry, Spring, Microservices etc.
This supersedes my former PR #625.

Add Pivotal Engineering Blog https://engineering.pivotal.io

---

README.md
engineering_blogs.opml

Julia Evans writes about OS related topics at https://jvns.ca

Add Julia Evans's blog

---

README.md
engineering_blogs.opml

Writes security related stuff at https://idea.popcount.org/

Add Marek Majkowski's blog

---

README.md
engineering_blogs.opml

Just adding one more blog I read at times :grinning:

Add Mary Rose Cook's blog

---

README.md

According to wikipedia, https://en.wikipedia.org/wiki/List_of_largest_Internet_companies, Asos is part of the largest Internet Companies.

Add Asos to the list

---

README.md
engineering_blogs.opml

https://medium.com/yammer-engineering

Add Yammer engineering blog.

---

README.md
engineering_blogs.opml

Add Trello engineering blog

---

README.md

Added the RoseHosting blog https://www.rosehosting.com/blog/

Add the RoseHosting blog

---

README.md
engineering_blogs.opml

https://engineering.squarespace.com/

Add Squarespace engineering blog

---

README.md
engineering_blogs.opml

As titled. The previous blog hasn't been updated since November, 2015. Please, review this change!
Thank you.

Update URL of PayPal engineering blog

---

README.md
engineering_blogs.opml

As titled. Please, review this PR.
Thank you.

Add commercetools tech blog

---

README.md
engineering_blogs.opml

We updated the url. Please review!

Update 8th Light blog URL

---

README.md
engineering_blogs.opml

Documenting progress of development on the new open source Linode Manager and the Linode API alpha

Add Linode Engineering blog

---

contributing.md

Additional steps if you'd like to have them in the contributing file. Feel free to tweak or reject.

Add Docker OPML generation steps

---

README.md
engineering_blogs.opml

Why This Blog Should Be Added:  This blog contains only development related content from our diverse development staff.  We discuss topics related to Ruby, Elixir, Java, Devops and more.

Adding Wombat Security

---

README.md
engineering_blogs.opml

Adds Jet Technology. Topics: Azure, Docker, Cloud, microservices, Event Source, F#

Add Jet Technology

---

README.md
engineering_blogs.opml

Luciano Mammino (me) is a software engineer who loves to write and share tecnical content especially regarding javascript, node.js, bash, php and symfony. He is also the co-author of the book [Node.js design patterns](https://www.nodejsdesignpatterns.com) published by Packt.
He is currently working as senior software engineer at [Planet 9 Energy](http://planet9energy.com) and sspending a lot of time with technologies such aws, aws lambda and serverless framework which will be the main topics for a series of upcoming articles on his blog.
He is also working on a semi-automated tech newsletter which will provide 7 interesting tech/programming content a week.

Added Luciano Mammino (loige.co)

---

README.md

Blog about App Development, Cloud, Cognitive, Data & Analytics and more...

IBM developerWorks added

---

README.md
engineering_blogs.opml

Sqreen engineering blog covers topics related to: 
* Security for developers
* Ruby / Rails development
* Python development
* Node.js development
Some example of past posts include: 
* Building a Dynamic Instrumentation Agent for Python
* How to prevent NoSQL injections in MongoDB in a Node.js app
* Building a Dynamic Instrumentation Agent for Ruby
* Identify Tor connections in Node.js with Tor-test
* MongoDB will not prevent NoSQL injections in your Node.js app

Added Sqreen Engineering Blog

---

README.md
engineering_blogs.opml

This is the request to add HomeAway's engineering blog. Cheers

Adding HomeAway

---

README.md
engineering_blogs.opml

Avenue Code is the leading software consulting agency focused on delivering end-to-end e-commerce solutions for enterprise organizations of all kinds. We have guided Fortune 500 companies through their software innovation journeys since we first opened for business in 2008.

Added the AvenueCode

---

README.md

Add convox blog to company list

---

README.md
engineering_blogs.opml

This blog contains a lot of good posts on spring, hibernate, JPA

Add Vlad Mihalcea blog

---

README.md
engineering_blogs.opml

Blog which explores and documents the odd parts of Ruby, which is helpful for everyone who wants to master this rather complex programming language

Add Idiosyncratic Ruby

---

README.md
engineering_blogs.opml

As titled. Please, review this PR!
Thanks.

Add Curalate's engineering blog

---

README.md

In CodeFX I write about software development in general and Java in particular.

Add codefx.org

---

README.md
engineering_blogs.opml

Hi,
This adds Deezer's engineering blog & feed entry.
It contains interesting topics about technical questions (scalability, music related subjects, etc.) and development workflow.
Cheers,
David

Add Deezer engineering blog

---

README.md

Airtame company engineering blog - contains 100% technical content

Add Airtame blog

---

README.md
engineering_blogs.opml

Domenico Luciani (me), young passionate programmer, 24 years old at the moment, he currently works as Software Engineer for Intesa SanPaolo. Graduated in Computer Science at University of Palermo. Computer Vision enthusiast, he loves security and often pen-tests too; in his free time he takes part of bounty programs for many companies. Maker and Raspberry pi owner.
He loves to write about nodejs, golang, security, personal experiences and computer vision.
Technical reviewer for PACKT (Actually he helps to publish 3 books about BBD, ECMAScript6 and OpenCV)

Added Domenico Luciani (domenicoluciani.com)

---

README.md
engineering_blogs.opml

add PicCollage (https://pic-collage.com) Tech Blog in the list
https://tech.pic-collage.com/

add PicCollage company

---

README.md

Added react native blog link to "R-Technologies"

Added React Native blog link

---

README.md
engineering_blogs.opml

Our technical blog about Ruby, and Elixir ! It's little new for us, but we try to add every month a new article :) !

Add JobTeaser technical blog

---

README.md
engineering_blogs.opml

Add SitePoint

---

README.md

Added link to go programming language blog.

added go programming language blog

---

README.md
engineering_blogs.opml

Grab is South-east Asia's largest rail-hailing startup and they deal with a lot of interesting problems at scale.

Add Grab Engineering Blog

---

README.md
engineering_blogs.opml

As titled, please review this PR!
Thank you

Add Heap's engineering blog

---

README.md
engineering_blogs.opml

This PR contains link to SmartRecruiters engineering blog "Smart Up" https://up.smartrecruiters.com
Smart Up includes pieces from our development team in Krakow and across the world.

Add SmartRecruiters engineering blog

---

Gemfile.lock
README.md
engineering_blogs.opml

It has a lot of Angular and Javascript posts from beginner to advanced level

Add Todd Motto blog:

---

README.md
engineering_blogs.opml

talks about emacs, angularjs, angular, javascript, web development, also runs Learning AngularJS newsletter (100+ subscribers)
let me know if there's some particular criteria to meet to get this accepted.
thanks!

add Rudolf Olah's angular/web dev blog

---

Gemfile
Gemfile.lock
generate_opml.rb

1) Remove Google Feed API attempt and kill some unnecessary deps too - this has been deprecated since December 2016 (https://developers.google.com/feed/)
2) Safely close XML file after reading it in
3) Some clean up of Ruby

Update generator script

---

README.md
engineering_blogs.opml

I hope you'll add the [Pusher blog](https://making.pusher.com/) to the blog collection as I think we post high quality content focused on our engineering problems and how we solve them. Thanks

add pusher blog

---

README.md
engineering_blogs.opml

* Scrapinghub https://blog.scrapinghub.com/

Add Scrapinghub blog

---

README.md
engineering_blogs.opml

As titled, please, review this blog. Thank you.

Add Dragan Djuric's blog

---

README.md
engineering_blogs.opml

Hi
I'm adding my personal technical blog - https://blog.pchudzik.com
I'm writing about technical stuff only. Mostly about Java, JVM, javascript, software development best practices.
Hope you'll find it useful :)

Added Paweł's Chudzik blog

---

README.md
engineering_blogs.opml

As titled, please, review this PR. Thank you.

Add Matthew Green's blog

---

README.md

Hi,
Please add my blog [Amit Merchant](https://www.amitmerchant.com/) where I post about my learnings from day to day tasks in my work life.
Thanks!

Add Blog of Amit Merchant

---

README.md
engineering_blogs.opml

I updated blog address of Andrey Akinshin. With updated blog address, we can get RSS feed.

Update blog address of Andrey Akinshin

---

README.md
engineering_blogs.opml

Added Blender blog Companies list

Blender blog added in Companies list

---

README.md
engineering_blogs.opml

The tech category of the Runtastic BLOG including topics around iOS, Android, Ember, Ruby, Infrastructure, Testing and Data Engineering.

Add Runtastic https://www.runtastic.com/blog/en/category/tech/

---

README.md
engineering_blogs.opml

- Geoblink Tech: https://tech.geoblink.com/

Add Geoblink tech blog

---

README.md
engineering_blogs.opml

[Addepar](https://addepar.com/) is working on building the platform for finance and we share our learnings on our new Engineering blog, [Build@Addepar](https://medium.com/build-addepar). We talk about Ember, data, and there will be much more in the future!

Add Addepar Engineering blog - Build@Addepar

---

README.md
engineering_blogs.opml

This is a technical blog that covers challenges across the full stack.
A majority of current posts covers DB-related challenges and lessons
learned (in particular, focusing on Postgres and DynamoDB).
Note: I also fixed a whitespace error for "Freeletics". Their blog
ended up in the opml file too after I fixed the whitespace error.

Add Affinity engineering blog

---

README.md
engineering_blogs.opml

Red Programming Language is a promising high level programming language inspired by Rebol with built-in GUI support. It is in active development and deserves recognition.
Note: I put this in a separate PR and closed the older one.

Add The Red Programming Language

---

README.md
engineering_blogs.opml

Added kotlin in technologies list

Kotlin link added in technologies list

---

README.md
engineering_blogs.opml

#Long standing blog focused on JavaScript and Web technologies.
I neglected to add the justification to the original commit message (as per the `contributing.md`). ~~I have one more PR I will make without the justification and some more on the way that will have this corrected.~~

Add Pony Foo group blog

---

README.md
engineering_blogs.opml

I am unsure why Freeletics's engineering blog was removed, this is a PR to add their blog back again.

Add Freeletics Engineering blog again

---

README.md

Coinbase is a leading cryptocurrency exchange service. The engineering blog talks about security, scaling, and system availability concerns.
https://engineering.coinbase.com

Add Coinbase

---

README.md
engineering_blogs.opml

Shazam is a Music discovery platform. They can instantly recognise any song from their vast library of 30 million songs.
Some of their blog posts - https://blog.shazam.com/behind-the-scenes-of-shazams-real-time-lyrics-feature-8feeb628ad

Add Shazam's engineering blog

---

README.md
engineering_blogs.opml

He is full-stack web developer, specializing on PHP. 
Books writer, author of PHP OOP Way and Event-driven PHP with ReactPHP.

Add Sergey Zhuk (http://sergeyzhuk.me/)

---

README.md

Blog and YT chanel about InfoSec/Hacking/Security

Added LiveOverflow Blog

---

README.md

Notes on computer forensics - international edition

Adding Blog of Andreas Schuster

---

README.md
engineering_blogs.opml

Add Envoy.

---

README.md

Blog about red teaming, penetration testing, and security research.

Adding Blog of Bohops

---

README.md
engineering_blogs.opml

This PR adds the [HERE developer blog](https://developer.here.com/blog).

add HERE developer blog

---

README.md

Blog about homelab and networking.

Adding Blog of Monstermuffin

---

README.md
engineering_blogs.opml

Hey,
Thank you for this great list, I thought I might just add Mesosphere here :)

Blog of Mesosphere

---

README.md
engineering_blogs.opml

Hey,
I thought I just leave some self-promotion here. I mostly blog about React and React Native stuff :)

Blog of Daniel Schmidt

---

README.md
engineering_blogs.opml

Blog offers interesting discussion on how SQL can be used for time-series.

Add Timescale blog

---

README.md
engineering_blogs.opml

**About the blog:**
Every once and a while, a group of _fraudengineers_ and data _zaientists_ get together and write about software engineering, data science and other cool stuff.
**About the company:**
Feedzai is AI (https://feedzai.com/). We’re coding the future of commerce with a leading platform powered by artificial intelligence and big data. Founded and developed by data scientists and aerospace engineers, Feedzai has one critical mission: make commerce safe. The world’s largest banks, payment providers and retailers use Feedzai’s machine learning technology to manage risks associated with banking and shopping, whether it’s in person, online or via mobile devices.

Added Feedzai tech blog.

---

README.md
engineering_blogs.opml

DoorDash frequently make update on their engineering blog about company engineering challenges and solutions.It would be good addition for this repo.

doordash-company-engineering-blog

---

README.md
engineering_blogs.opml

Serverless blog from serverless company. Serverless is open source tool to build and deploy code on lambda/google function/azure function,etc . Really helpful for all the people who are using exploring serverless as framework for deployment and writing code.

Serverless company blog

---

README.md
engineering_blogs.opml

[Hasura's blog](https://blog.hasura.io/) has a lot of engineering content related to GraphQL and Kubernetes

Add Hasura

---

README.md
engineering_blogs.opml

1. **Stack Decisions** : 
where developers  from around the globe(mostly big tech) share their reasoning around the tools to they use/used. 
2. **Articles** which features posts on detailed updates on various tools.

Stackshare developer blog and developer decisions

---

README.md
engineering_blogs.opml

This PR adds @doximity's engineering blog to the list.

Add Doximity engineering blog

---

README.md
engineering_blogs.opml

Adding Postman's technical blog

Adding postman

---

README.md
engineering_blogs.opml

Update Criteo tech blog

---

README.md
engineering_blogs.opml

Removes Bloomreach Engineering Blog from the list.
Fixes #922

Remove Bloomreach

---

README.md
engineering_blogs.opml

This is my personal blog with software and networking related topics

[added] https://schakko.de

---

README.md
engineering_blogs.opml

Thank you for maintaining this list!
I added my personal blog.
In contribution guidelines, it is mentioned that the personal website should have a decent number of followers. Last year I had over [100k users](https://muffinman.io/public/img/2020/analytics.png)
Cheers!

Added muffinman.io

---

README.md
engineering_blogs.opml

Add tania.dev, 5000+ subscribers.
Glenn's blog was also automatically updated when I generated the opml.

Add Tania Rascia
